In [9]:
import sys
!{sys.executable} -m pip install transformers

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 134.8/134.8 kB 4.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.8/8.8 MB 15.4 MB/s eta 0:00:000:00:010:00:01:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 393.3/393.3 kB 10.5 MB/s eta 0:00:00


In [1]:
!wget https://media.githubusercontent.com/media/nadavbra/proteinbert_data_files/master/epoch_92400_sample_23500000.pkl

--2024-04-04 09:56:19--  https://media.githubusercontent.com/media/nadavbra/proteinbert_data_files/master/epoch_92400_sample_23500000.pkl
Resolving media.githubusercontent.com (media.githubusercontent.com)... 185.199.109.133, 185.199.111.133, 185.199.110.133, ...
Connecting to media.githubusercontent.com (media.githubusercontent.com)|185.199.109.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 191800918 (183M) [application/octet-stream]
Saving to: ‘epoch_92400_sample_23500000.pkl’

epoch_92400_sample_ 100%[===================>] 182,92M  15,3MB/s    in 14s     

2024-04-04 09:56:45 (13,2 MB/s) - ‘epoch_92400_sample_23500000.pkl’ saved [191800918/191800918]



In [7]:
import pickle
with open('epoch_92400_sample_23500000.pkl','rb') as fh:
    n_annotations, model_weights, optimizer_weights = pickle.load(fh)
# [p.shape for p in model_weights]

In [ ]:
from transformers import BertModel, BertTokenizer
import re
tokenizer = BertTokenizer.from_pretrained("Rostlab/prot_bert", do_lower_case=False )
model = BertModel.from_pretrained("Rostlab/prot_bert")

In [35]:
seq = "A T G G A T"
seq = re.sub(r"[UZOB]", "X", seq)
print(seq)
encoded_input = tokenizer(seq, return_tensors='pt')

output = model(**encoded_input)

output.last_hidden_state.shape

A T G G A T


torch.Size([1, 8, 1024])

In [34]:
encoded_input

{'input_ids': tensor([[ 2,  6, 15,  7,  7,  6, 15,  3]]), 'token_type_ids': tensor([[0, 0, 0, 0, 0, 0, 0, 0]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1]])}

In [36]:
tokenizer.get_vocab()

{'[PAD]': 0,
 '[UNK]': 1,
 '[CLS]': 2,
 '[SEP]': 3,
 '[MASK]': 4,
 'L': 5,
 'A': 6,
 'G': 7,
 'V': 8,
 'E': 9,
 'S': 10,
 'I': 11,
 'K': 12,
 'R': 13,
 'D': 14,
 'T': 15,
 'P': 16,
 'N': 17,
 'Q': 18,
 'F': 19,
 'Y': 20,
 'M': 21,
 'H': 22,
 'C': 23,
 'W': 24,
 'X': 25,
 'U': 26,
 'B': 27,
 'Z': 28,
 'O': 29}

In [38]:
set(model.parameters())

{Parameter containing:
 tensor([ 0.0003,  0.0254,  0.1621,  ..., -0.0082,  0.0174, -0.0704],
        requires_grad=True),
 Parameter containing:
 tensor([ 0.0008,  0.0249, -0.1553,  ...,  0.0201, -0.2530,  0.0699],
        requires_grad=True),
 Parameter containing:
 tensor([ 0.0012, -0.0043, -0.0036,  ...,  0.0847,  0.0716,  0.0001],
        requires_grad=True),
 Parameter containing:
 tensor([ 0.0013, -0.0149,  0.0130,  ..., -0.0263, -0.0365,  0.0130],
        requires_grad=True),
 Parameter containing:
 tensor([ 0.0017, -0.0033,  0.0132,  ...,  0.0126,  0.0498, -0.0196],
        requires_grad=True),
 Parameter containing:
 tensor([ 0.0026,  0.0683, -0.1499,  ...,  0.0346, -0.1046,  0.0905],
        requires_grad=True),
 Parameter containing:
 tensor([ 0.0029, -0.0030,  0.0353,  ...,  0.0171,  0.0541, -0.0394],
        requires_grad=True),
 Parameter containing:
 tensor([ 0.0029, -0.0377,  0.0359,  ...,  0.0732, -0.0470, -0.0544],
        requires_grad=True),
 Parameter containing:
 